services:
  platform-api:
    build:
      context: ../platform-api
      dockerfile: Dockerfile.local

  telemetry-ingester:
    build:
      context: ../telemetry-ingester
      dockerfile: Dockerfile.local

  bot-worker:
    build:
      context: ../bot-worker
      dockerfile: Dockerfile.local
